// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK7QFy3tuILvS6-6GY-SSCdhuwKCy1nvA',
    appId: '1:856946629037:web:32149d0ae04d92f44b2924',
    messagingSenderId: '856946629037',
    projectId: 'travelapp-756e5',
    authDomain: 'travelapp-756e5.firebaseapp.com',
    storageBucket: 'travelapp-756e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeoAbo-7GVp2uvw6EcQwTaAN4gNz2GTdY',
    appId: '1:856946629037:android:d45a54e8930cc3dd4b2924',
    messagingSenderId: '856946629037',
    projectId: 'travelapp-756e5',
    storageBucket: 'travelapp-756e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8VALnlS73CXzWBSJrfmOUeT9mSAZwwkM',
    appId: '1:856946629037:ios:5a8a085411ea28054b2924',
    messagingSenderId: '856946629037',
    projectId: 'travelapp-756e5',
    storageBucket: 'travelapp-756e5.appspot.com',
    iosBundleId: 'com.example.travelsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8VALnlS73CXzWBSJrfmOUeT9mSAZwwkM',
    appId: '1:856946629037:ios:5a8a085411ea28054b2924',
    messagingSenderId: '856946629037',
    projectId: 'travelapp-756e5',
    storageBucket: 'travelapp-756e5.appspot.com',
    iosBundleId: 'com.example.travelsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK7QFy3tuILvS6-6GY-SSCdhuwKCy1nvA',
    appId: '1:856946629037:web:bc78043788591e954b2924',
    messagingSenderId: '856946629037',
    projectId: 'travelapp-756e5',
    authDomain: 'travelapp-756e5.firebaseapp.com',
    storageBucket: 'travelapp-756e5.appspot.com',
  );
}
